default_context:
  author: "name"
  email: "test@example.com"
  project: "startercookie"
  description: "Example for project start."
  python_version: "3.11"
  do_modelling: "yes"
  use_precommit: "yes"
  use_dvc: "yes"